import React, { useState } from 'react'
import AddProducts from './AddProducts'
import DeleteProducts from './DeleteProducts'
import EditProduct from './EditProduct'
import Logout from './Logout'
import AllUsers from './AllUsers'
